---
title: "Preliminary EDA"
author: "Tanya Wang"
output: 
    html_notebook:
    fig_height: 6
    fig_width: 10
---
---

## Introduction

### Research Question
#### **How do the number of languages spoken at home affect English speaking ability?**
I want to see how the number of languages and the type of language(s) spoken at home can affect a person's ability to speak English well. I have a couple data sources to analyze that, one based on counties in the US, one based on the states in the US, and one of the US (the nation) overall. I may look for more datasets to add so that there's a bit more "color" and makes the entire project more interesting.

## The Data

First we need clean the environment and then load the package(s) we need. Below is a description of each package I loaded and what it is used for:

- **tidyverse:** this is a collection of R packages designed for data science. It includes ggplot2, dplyr, tidyr, and more that we can use for everyday data analyses.
```{r}
rm(list = ls())

library(tidyverse)

```


### Questions
- where did it come from?
- who collected/maintains them?
- when & why were they originally collected?
- what does a case represent in each data source, & how many total cases are available?
- what are some of the variables that I plan to use?


## Preliminary Observations

### Plots & Summary Statistics
